# Site settings
title: Timothy F. Davison
author: Timothy F. Davison
email: your-email@example.com
description: >- 
  And now I am become blog, writer of trash thought pieces.
baseurl: ""
url: "https://timothyfdavison.com"
lang: en
timezone: America/New_York

# Social media and SEO
twitter_username: 
github_username: timothyfdavison
linkedin_username: timothy-davison-a318aa142
google_analytics:
comments: false

# SEO settings
twitter:
  username: 
  card: summary
logo: /assets/tim_portrait.jpg
social:
  name: Timothy F. Davison
  links:
    - https://github.com/timothyfdavison
    - https://www.linkedin.com/in/timothy-davison-a318aa142/

# Build settings
remote_theme: yous/whiteglass
plugins:
  - jekyll-remote-theme
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# Exclude options
exclude:
  - README.md
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Outputting
permalink: /:year/:month/:day/:title/

# Markdown settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
kramdown:
  auto_ids: false
  enable_coderay: false
  entity_output: as_char
  footnote_nr: 1
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  toc_levels: 1..6

# jekyll-archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# jekyll-paginate
paginate_path: /posts/:num/
paginate: 5
